export const DIALOGS_SET_ITEMS = "DIALOGS_SET_ITEMS";
export const DIALOG_SET_ITEM = "DIALOG_SET_ITEM";
export const MESSAGES_SET_ITEMS = "MESSAGES_SET_ITEMS";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
export const MESSAGE_SET_ITEM = "MESSAGE_SET_ITEM";
export const USER_SET_DATA = "USER_SET_DATA";
